name = input('Qual''è il tuo nome?\n')
print('               ')
print('Salve Signore %s.' % name)
print('               ')
age = input('Quanti anni ha?')
print('               ')
print('Lei si chiama %s.' % name)
print('               ')
print('Ed ha %s Anni' % age) 
print('               ')
gender = input('Ok quindi lei è maschio o femmina o No-Gender?')
print('               ')
print('Quindi ecco le sue informazioni:')
print('               ')
print('Lei si chiama %s' % name)
print('Ha %s Anni ' % age)
print('               ')
print('               ')
print('Grazie per aver usato questo servizio')
print('               ')
print('               ')
print('               ')
print('               ')
print('Fatto con il 🧡 da FiokoLy')
